- name: Ensure certs directory exists
  file:
    path: "{{ wazuh_cert_dir }}"
    state: directory
    mode: '0755'

- name: Download wazuh-certs-tool.sh
  get_url:
    url: "https://packages.wazuh.com/4.12/wazuh-certs-tool.sh"
    dest: "{{ wazuh_cert_dir }}/wazuh-certs-tool.sh"
    mode: '0755'

- name: Generate Wazuh certificates (idempotent)
  command: "./wazuh-cert-tool.sh -A"
  args:
    chdir: "{{ wazuh_cert_dir }}"
  creates: "{{ wazuh_cert_dir }}/root-ca.pem"

- name: Create Docker secrets from generated certs
  docker_secret:
    name: "{{ item }}"
    state: present
    data: "{{ lookup('file', wazuh_cert_dir + '/' + item) }}"
  loop:
    - root-ca.pem
    - wazuh.manager.pem
    - wazuh.manager-key.pem
    - wazuh.indexer.pem
    - wazuh.indexer-key.pem
    - wazuh.dashboard.pem
    - wazuh.dashboard-key.pem

- name: Deploy Wazuh stack file
  template:
    src: wazuh-stack.yml.j2
    dest: "{{ wazuh_stack_file }}"

- name: Deploy Wazuh stack
  command: docker stack deploy -c {{ wazuh_stack_file }} wazuh
