---
- name: Ensure certs directory exists
  file:
    path: "{{ wazuh_cert_dir }}"
    state: directory
    mode: '0755'

- name: Download wazuh-certs-tool.sh
  get_url:
    url: "https://packages.wazuh.com/4.12/wazuh-certs-tool.sh"
    dest: "{{ wazuh_cert_dir }}/wazuh-certs-tool.sh"
    mode: '0755'

- name: Deploy Wazuh cert configuration
  copy:
    dest: "{{ wazuh_cert_dir }}/config.yml"
    content: |
      nodes:
        indexer:
          - name: wazuh.indexer
            ip: 127.0.0.1

        server:
          - name: wazuh.manager
            ip: 127.0.0.1

        dashboard:
          - name: wazuh.dashboard
            ip: 127.0.0.1

- name: Debug - Show cert directory contents before generation
  command: ls -la "{{ wazuh_cert_dir }}"
  register: cert_dir_before
  
- name: Debug - Show cert directory contents before generation
  debug:
    var: cert_dir_before.stdout_lines

- name: Generate Wazuh certificates (idempotent)
  command: "./wazuh-certs-tool.sh -A"
  args:
    chdir: "{{ wazuh_cert_dir }}"
    creates: "{{ wazuh_cert_dir }}/wazuh-certificates/root-ca.pem"
  register: cert_generation_result

- name: Debug - Show certificate generation output
  debug:
    var: cert_generation_result

- name: Check if certificates directory exists
  stat:
    path: "{{ wazuh_cert_dir }}/wazuh-certificates"
  register: ansible_stat_result

- name: Fix ownership of generated certificates directory
  file:
    path: "{{ wazuh_cert_dir }}/wazuh-certificates"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
    recurse: yes
  when: ansible_stat_result.stat.exists

- name: Debug - List contents of cert directory
  command: find "{{ wazuh_cert_dir }}" -type f -name "*.pem"
  register: cert_files_found
  ignore_errors: yes

- name: Debug - Show found certificate files
  debug:
    var: cert_files_found.stdout_lines

- name: Debug - List wazuh-certificates directory contents
  command: ls -la "{{ wazuh_cert_dir }}/wazuh-certificates/"
  register: cert_dir_contents
  ignore_errors: yes

- name: Debug - Show wazuh-certificates directory contents
  debug:
    var: cert_dir_contents.stdout_lines

- name: Create Docker secrets from generated certs
  docker_secret:
    name: "{{ item }}"
    state: present
    data: "{{ lookup('file', wazuh_cert_dir + '/wazuh-certificates/' + item) }}"
  loop:
    - root-ca.pem
    - wazuh.manager.pem
    - wazuh.manager-key.pem
    - wazuh.indexer.pem
    - wazuh.indexer-key.pem
    - wazuh.dashboard.pem
    - wazuh.dashboard-key.pem
  when: cert_files_found.stdout_lines | length > 0

- name: Deploy Wazuh stack file
  template:
    src: wazuh-stack.yml.j2
    dest: "{{ wazuh_stack_file }}"

- name: Deploy Wazuh stack
  command: docker stack deploy -c {{ wazuh_stack_file }} wazuh
