---
- name: Install dependencies
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common"]
    state: present
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: present
    update_cache: yes


- name: Check if Swarm is already initialized
  command: docker info --format '{{ "{{" }}.Swarm.LocalNodeState{{ "}}" }}'
  register: swarm_status
  changed_when: false
  ignore_errors: yes

- name: Init Swarm
  command: docker swarm init --advertise-addr {{ ansible_host }}
  register: swarm_init
  when: swarm_status.stdout != "active"

- name: Deploy Wazuh generator
  copy:
    src: "{{ role_path }}/templates/cert-generator.yml.j2"
    dest: /home/{{ ansible_user }}/cert-generator.yml
    mode: 0644

- name: Deploy Wazuh generator on Docker Swarm
  command: docker stack deploy -c cert-generator.yml wazuh-generator

- name: Deploy Wazuh stack
  copy:
    src: "{{ role_path }}/templates/docker-compose.yml.j2"
    dest: /home/{{ ansible_user }}/docker-compose.yml
    mode: 0644

- name: Deploy Wazuh stack on Docker Swarm
  command: docker stack deploy -c docker-compose.yml wazuh

