# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install ansible

      # Setup SSH key for Ansible
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          # You'll need to add your SSH private key as a GitHub secret
          # echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ~/.ssh/id_ed25519
          # chmod 600 ~/.ssh/id_ed25519
          
      # Run Docker setup playbook
      - name: Run Docker setup playbook  
        run: |
          cd ansible
          # Note: You may need to update inventory/hosts.ini to include wazuh-node hosts
          # or modify the playbook to target existing hosts
          ansible-playbook -i inventory/hosts.ini playbooks/docker-setup.yml --become
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
