# This is a basic workflow to help you get started with Actions

name: Deploy to swarm

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted  # Your VM1 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create vault password file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/vault_pass
          chmod 600 /tmp/vault_pass

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.ini playbooks/deploy-swarm.yml --vault-password-file /tmp/vault_pass

      - name: Clean up vault password file
        if: always()
        run: |
          rm -f /tmp/vault_pass
